### ISSUE TITLE
Consider adding fxddit to fix reddit embeds

### ISSUE THREAD

**Issue by aqsd91** [wotanut/DiscordStuff#10]
Similarly to vx/fxtwitter, fxddit fixes reddit embeds in discord. Here's a link to the repo [fxddit repo](https://github.com/MinnDevelopment/fxreddit).
From my limited testing simply adding `msgcontent = msgcontent.replace("https://www.reddit.com", "https://www.rxddit.com");` works

**Comment by wotanut** [comment]
Since this pr was opened (and since the project started) there are now two plugins that I think can do this better than this one:

- [SocialMediaLinkConverter](https://betterdiscord.app/plugin/SocialMediaLinkConverter)
- [TextReplacer](https://betterdiscord.app/plugin/TextReplacer)

I think that this should be included there instead of on this plugin as it's more relevant to them
