### ISSUE TITLE
[IMPROVEMENT] - removeTrackingURL.plugin.js

### ISSUE THREAD

**Issue by Obegg** [wotanut/DiscordStuff#16]
[removeTrackingURL.plugin.js](https://raw.githubusercontent.com/wotanut/DiscordStuff/refs/heads/main/plugins/dist/removeTrackingURL.plugin.js) is using [0PluginLibrary.plugin.js](https://raw.githubusercontent.com/zerebos/BDPluginLibrary/refs/heads/master/release/0PluginLibrary.plugin.js).

According to the [README](https://github.com/zerebos/BDPluginLibrary/blob/master/README.md):

> [!CAUTION]
> This library has reached end of life and is now considered deprecated and discontinued. It is recommended to convert over to using BetterDiscord's built-in API. If you find there are features missing, open a feature request in the BetterDiscord repository.

**Comment by wotanut** [comment]
I don't see much of a point in this tbh. It would be painful to have to migrate to a whole new library when


- I don't intend to add any new features
- The original library still works as is (haven't had any bug reports to say otherwise)

If you want you can rewrite it using the BD api and submit a pull request though, I won't stop you.
